'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
import {useIdentity} from './Providers';
type Goal={goal:string;weekly_target:number;questions_retried:number;attempts:number;week_start:string;resets_at:string};
export default function LearningGoal(){
 const [data,setData]=useState<Goal|null>(null),[goal,setGoal]=useState(''),[target,setTarget]=useState(3),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const blocked=useIdentity()?.privacy?.deletion_request?.status==='pending';
 function received(value:Goal){setData(value);setGoal(value.goal);setTarget(value.weekly_target||3);}
 async function load(){try{received(await api<Goal>('/learning-goal'));setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function save(pause=false){if(busy)return;setBusy(true);setError('');setNotice('');try{received(await api<Goal>('/learning-goal',{goal:goal.trim(),weekly_target:pause?0:target}));setEditing(false);setNotice(pause?'Weekly target paused. Your attempts stay saved.':'Goal saved. All questions you retry this week count toward it.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="learning-goal settings-card"><h2>Your weekly practice goal</h2><p>Pick a focus and a small target. Each different saved answer you retry counts once per week, across all topics.</p>{!data&&!error&&<p role="status">Loading your goal…</p>}{data&&<>{data.weekly_target>0?<><h3>{data.goal}</h3><p><strong>{data.questions_retried} / {data.weekly_target}</strong> questions retried this week{data.questions_retried>=data.weekly_target?' · Target reached':''}</p><progress max={data.weekly_target} value={Math.min(data.questions_retried,data.weekly_target)} aria-label="Weekly questions retried"/><p className="field-help">Resets Monday at 00:00 UTC ({new Date(data.resets_at).toLocaleString()} locally). Repeated attempts on the same saved answer do not increase the question count. This is an activity target, not a mastery score.</p><Link className="secondary" href="/saved">Choose a question</Link></>:<p>No active target. Practise at your own pace, or set a goal when it helps.</p>}
 {!editing?<div className="button-row"><button className="text-button" disabled={blocked} onClick={()=>setEditing(true)}>{data.weekly_target?'Change goal':'Set a weekly goal'}</button></div>:<form onSubmit={e=>{e.preventDefault();void save();}}><label htmlFor="learning-goal">What would you like to work on?</label><input id="learning-goal" maxLength={160} required value={goal} disabled={busy||blocked} onChange={e=>setGoal(e.target.value)} placeholder="For example, explaining my maths steps"/><label htmlFor="weekly-target">Different questions to retry per week</label><input id="weekly-target" type="number" min={1} max={50} required value={target} disabled={busy||blocked} onChange={e=>setTarget(Number(e.target.value))}/><div className="button-row"><button className="primary" disabled={busy||blocked||!goal.trim()||target<1||target>50}>{busy?'Saving…':'Save goal'}</button>{data.weekly_target>0&&<button type="button" className="secondary" disabled={busy||blocked} onClick={()=>void save(true)}>Pause target</button>}<button type="button" className="text-button" disabled={busy} onClick={()=>{received(data);setEditing(false);}}>Cancel</button></div></form>}</>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}{!data&&<button className="text-button" onClick={()=>void load()}>Retry goal</button>}</p>}</section>;
}
