'use client';
import {useState} from 'react';
import {api} from '@/lib/api';
import {SupportReport} from '@/lib/support';
type Page={items:SupportReport[];has_more:boolean};
export default function OperatorReports(){
 const [data,setData]=useState<Page|null>(null),[status,setStatus]=useState<'open'|'resolved'>('open'),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(nextStatus=status,nextOffset=offset){setBusy(true);setError('');try{const next=await api<Page>(`/operator/reports?status=${nextStatus}&offset=${nextOffset}`);setData(next);setStatus(nextStatus);setOffset(nextOffset);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function update(report:SupportReport){setBusy(true);setError('');try{await api(`/operator/reports/${report.id}`,{status:report.status==='open'?'resolved':'open'});await load(status,0);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details><summary>Review user reports</summary><p>Reports contain text users chose to share. Marking a report resolved changes its status; it does not email the user.</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>void load('open',0)}>Open reports</button><button className="secondary" disabled={busy} onClick={()=>void load('resolved',0)}>Resolved reports</button></div>{busy&&<p role="status">Updating reports…</p>}{error&&<p role="alert">{error}</p>}{data&&<><p>{status==='open'?'Open reports':'Resolved reports'}</p>{data.items.length===0?<p>No reports in this view.</p>:data.items.map(report=><article className="operator-report" key={report.id}><h3>{report.category.replace('_',' ')}</h3><p>{report.message}</p><p className="field-help">Report: {report.id}<br/>Account: {report.user_id}<br/>{report.reference&&<>Error reference: {report.reference}<br/></>}{new Date(report.created_at).toLocaleString()}</p><button className="secondary" disabled={busy} onClick={()=>void update(report)}>{report.status==='open'?'Mark resolved':'Reopen report'}</button></article>)}<div className="button-row"><button disabled={busy||offset===0} onClick={()=>void load(status,Math.max(0,offset-25))}>Previous</button><span>Page {Math.floor(offset/25)+1}</span><button disabled={busy||!data.has_more} onClick={()=>void load(status,offset+25)}>Next</button></div></>}</details>;
}
