'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from '@/lib/api';
import {scopedKey} from '@/lib/browserStorage';
import {SupportReport} from '@/lib/support';
import {useIdentity} from './Providers';
type Draft={id:string;category:SupportReport['category'];message:string;reference:string|null};
export default function ProblemReport(){
 const [category,setCategory]=useState<SupportReport['category']>('problem'),[message,setMessage]=useState(''),[reference,setReference]=useState(''),[reports,setReports]=useState<SupportReport[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const pending=useRef<Draft|null>(null),sending=useRef(false);
 const blocked=useIdentity()?.privacy?.deletion_request?.status==='pending';
 async function load(){try{setReports(await api<SupportReport[]>('/support/reports'));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();try{const raw=localStorage.getItem(scopedKey('report','pending'));if(raw){const draft=JSON.parse(raw) as Draft;if(typeof draft.id==='string'&&typeof draft.message==='string'&&['problem','suggestion','accessibility','ai_answer'].includes(draft.category)){pending.current=draft;setCategory(draft.category);setMessage(draft.message);setReference(draft.reference||'');setNotice('A previous report is ready to retry. The same reference prevents a duplicate.');}}}catch{setError('This browser could not restore an unfinished report.');}},[]);
 async function submit(){if(sending.current||blocked)return;sending.current=true;setBusy(true);setError('');setNotice('');try{const next={category,message:message.trim(),reference:reference.trim()||null};if(!pending.current||pending.current.category!==next.category||pending.current.message!==next.message||pending.current.reference!==next.reference)pending.current={...next,id:crypto.randomUUID()};localStorage.setItem(scopedKey('report','pending'),JSON.stringify(pending.current));const saved=await api<SupportReport>('/support/reports',pending.current);setReports(current=>[saved,...current.filter(report=>report.id!==saved.id)].slice(0,20));setNotice(`Report saved for operator review. Reference: ${saved.id}. No email was sent.`);setMessage('');setReference('');pending.current=null;try{localStorage.removeItem(scopedKey('report','pending'));}catch{/* A replay of the same saved ID is safe. */}}catch(e){setError((e as Error).message);}finally{sending.current=false;setBusy(false);}}
 return <section><form className="report-form" onSubmit={e=>{e.preventDefault();void submit();}}><label htmlFor="report-category">What would you like to report?</label><select id="report-category" value={category} disabled={busy||blocked} onChange={e=>setCategory(e.target.value as SupportReport['category'])}><option value="problem">Something is not working</option><option value="accessibility">Accessibility or mobile issue</option><option value="ai_answer">An AI answer problem</option><option value="suggestion">A suggestion</option></select><label htmlFor="report-message">What happened, and what did you expect?</label><textarea id="report-message" required minLength={10} maxLength={2000} value={message} disabled={busy||blocked} onChange={e=>setMessage(e.target.value)} aria-describedby="report-privacy"/><p id="report-privacy" className="field-help">Only what you enter here is shared with the workspace operator, along with your account ID. Do not include passwords, keys, or a full private conversation. No conversation text or browser logs are attached automatically.</p><label htmlFor="report-reference">Error reference, if shown (optional)</label><input id="report-reference" maxLength={36} pattern="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" value={reference} disabled={busy||blocked} onChange={e=>setReference(e.target.value)} placeholder="Copy the reference from the error message"/><button className="primary" disabled={busy||blocked||message.trim().length<10}>{busy?'Saving report…':'Save report for review'}</button>{blocked&&<p>New reports are paused while account data deletion is pending.</p>}</form>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}
 <section className="report-history"><h2>Your recent reports</h2><button className="text-button" disabled={busy} onClick={()=>{setError('');void load();}}>Refresh status</button><p className="field-help">The operator reviews these inside ThinkFirst. There is no automatic email or guaranteed response time. Contact support below if you need to follow up.</p>{reports.length===0?<p>No reports loaded.</p>:reports.map(report=><article key={report.id}><strong>{report.status==='resolved'?'Marked resolved':'Awaiting review'}</strong><p>{report.message}</p><small>{new Date(report.created_at).toLocaleString()} · Reference: {report.id}</small></article>)}</section></section>;
}
